project_name: gh-changelog

release:
  name_template: "gh-changelog {{.Version}}"
  prerelease: auto

before:
  hooks:
    - go mod tidy
    - go fmt ./...

builds:
  - id: changelog
    binary: "{{ tolower .Os }}-{{ .Arch }}"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    asmflags:
      - all=-trimpath={{.Env.WORKINGDIR}}
    gcflags:
      - all=-trimpath={{.Env.WORKINGDIR}}
    ldflags:
      - -s -w -X github.com/chelnak/gh-changelog/cmd.version={{.Version}}
    mod_timestamp: '{{ .CommitTimestamp }}'
    no_unique_dist_dir: true


archives:
  - format: binary
    name_template: "{{ tolower .Os }}-{{ .Arch }}"
    allow_different_binary_count: true

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-{{.ShortCommit}}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'