# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: ci

on:
  push:
    tags:
      - v*
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

env:
  GO_VERSION: 1.18

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest

      - name: test
        run: go test -v ./...

  release:
    name: release  
    runs-on: ubuntu-latest
    env:
      WORKINGDIR: ${{ github.workspace }}
    if: startsWith(github.ref, 'refs/tags/v')
    needs:
      - "lint"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}